INSERT ALL
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('ki', 0)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('gago', 1)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('jua345', 2)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('kkkus', 3)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('rameno', 4)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('tadeo', 5)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('semejis', 6)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('cataclism0', 7)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('lopera', 8)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('sameda', 9)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('ouita56', 10)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('darx666', 11)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('firehead', 12)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('sugoisugoi', 13)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('momo', 14)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('sabeta', 15)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('jugorta', 0)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('faas', 1)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('lopiunes', 2)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('grepa', 3)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('lopera', 4)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('sameda', 5)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('ouita56', 6)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('darx666', 7)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('firehead', 8)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('sugoisugoi', 9)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('momo', 10)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('sabeta', 11)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('jugorta', 12)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('faas', 13)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('lopiunes', 14)
into PERSONA_DISPONIBLEXOCUPACION
(USERNAME, OCUPACION_ID)
values
('grepa', 15)
SELECT 1 from DUAL;
