INSERT ALL
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(0, 0)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(0, 4)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(1, 0)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(2, 0)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(2, 4)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(3, 0)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(3, 4)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(4, 1)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(4, 2)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(5, 1)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(6, 1)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(7, 2)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(8, 2)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(9, 2)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(10, 2)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(11, 0)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(11, 4)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(12, 4)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(13, 4)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(14, 5)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(15, 5)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(16, 5)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(17, 5)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(18, 6)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(19, 6)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(20, 6)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(21, 7)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(22, 7)
into INTERESXCATEGORIA_INTERES
(INTERES_ID, CATEGORIA_INTERES_ID)
values
(23, 7)
SELECT 1 from DUAL;
