INSERT ALL
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('koki', 23)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('gago', 22)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('jua345', 21)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('kkkus', 20)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('rameno', 19)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('tadeo', 18)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('semejis', 17)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('cataclism0', 16)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('lopera', 15)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('sameda', 14)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('ouita56', 13)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('darx666', 12)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('firehead', 11)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('sugoisugoi', 10)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('momo', 9)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('sabeta', 8)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('jugorta', 7)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('faas', 6)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('lopiunes', 5)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('grepa', 4)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('lopera', 3)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('sameda', 2)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('ouita56', 1)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('darx666', 0)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('firehead', 23)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('sugoisugoi', 22)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('momo', 21)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('sabeta', 20)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('jugorta', 19)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('faas', 18)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('lopiunes', 17)
into PERSONA_DISPONIBLEXINTERES
(USERNAME, INTERES_ID)
values
('grepa', 16)
SELECT 1 from DUAL;
