INSERT ALL
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('koki', 7, 1)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('gago', 6, 2)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('jua345', 5, 3)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('kkkus', 4, 4)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('rameno', 3, 5)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('tadeo', 2, 6)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('semejis', 1, 7)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('cataclism0', 0, 8)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('lopera', 7, 9)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('sameda', 6, 10)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('ouita56', 5, 1)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('darx666', 4, 2)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('firehead', 3, 3)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('sugoisugoi', 2, 4)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('momo', 1, 5)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('sabeta', 0, 6)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('jugorta', 1, 7)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('faas', 2, 8)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('lopiunes', 3, 9)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('grepa', 4, 10)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('lopera', 5, 1)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('sameda', 6, 2)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('ouita56', 7, 3)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('darx666', 7, 4)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('firehead', 6, 5)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('sugoisugoi', 5, 6)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('momo', 4, 7)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('sabeta', 3, 8)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('jugorta', 2, 9)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('faas', 1, 10)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('lopiunes', 0, 66)
into PERSONA_DISPONIBLEXMASCOTA
(USERNAME, MASCOTA_ID, CANTIDAD)
values
('grepa', 2, 45)
SELECT 1 from DUAL;
