INSERT ALL
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(0, 0)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(1, 0)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(2, 1)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(3, 1)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(4, 2)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(5, 2)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(6, 2)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(7, 3)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(8, 4)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(9, 4)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(10, 3)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(10, 5)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(11, 5)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(12, 6)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(13, 6)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(14, 6)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(14, 7)
into OCUPACIONXCATEGORIA_OCUPACION
(OCUPACION_ID, CATEGORIA_OCUPACION_ID)
values
(15, 7)
SELECT 1 from DUAL;
