INSERT ALL
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('koki', 9)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('gago', 8)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('jua345', 7)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('kkkus', 6)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('rameno', 5)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('tadeo', 4)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('semejis', 3)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('cataclism0', 2)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('lopera', 1)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('sameda', 0)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('ouita56', 9)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('darx666', 8)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('firehead', 7)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('sugoisugoi', 6)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('momo', 5)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('sabeta', 4)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('jugorta', 3)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('faas', 2)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('lopiunes', 1)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('grepa', 0)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('lopera', 9)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('sameda', 8)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('ouita56', 7)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('darx666', 6)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('firehead', 5)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('sugoisugoi', 4)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('momo', 3)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('sabeta', 2)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('jugorta', 1)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('faas', 0)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('lopiunes', 9)
into PERSONA_DISPONIBLEXEJERCICIO
(USERNAME, EJERCICIO_ID)
values
('grepa', 8)
SELECT 1 from DUAL;
