INSERT ALL
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(0, 'Ciencia/Tecnología')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(1, 'Administración')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(2, 'Salud')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(3, 'Educación')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(4, 'Ciencias sociales')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(5, 'Lenguaje/Literatura')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(6, 'Política')
into CATEGORIA_OCUPACION
(CATEGORIA_OCUPACION_id, NOMBRE)
values
(7, 'Derecho')
SELECT 1 from DUAL;
