INSERT ALL
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('koki', 29)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('gago', 28)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('jua345', 27)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('kkkus', 26)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('rameno', 25)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('tadeo', 24)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('semejis', 23)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('cataclism0', 22)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('lopera', 21)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('sameda', 20)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('ouita56', 19)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('darx666', 18)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('firehead', 17)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('sugoisugoi', 16)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('momo', 15)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('sabeta', 14)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('jugorta', 13)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('faas', 12)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('lopiunes', 11)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('grepa', 10)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('lopera', 9)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('sameda', 8)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('ouita56', 7)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('darx666', 6)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('firehead', 5)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('sugoisugoi', 4)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('momo', 3)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('sabeta', 2)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('jugorta', 1)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('faas', 0)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('lopiunes', 23)
into PERSONA_DISPONIBLEXRELIGION
(USERNAME, RELIGION_ID)
values
('grepa', 22)
SELECT 1 from DUAL;
