INSERT ALL
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('koki', 0)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('gago', 1)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('jua345', 2)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('kkkus', 3)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('rameno', 4)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('tadeo', 5)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('semejis', 6)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('cataclism0', 7)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('lopera', 8)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('sameda', 0)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('ouita56', 1)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('darx666', 2)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('firehead', 3)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('sugoisugoi', 4)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('momo', 5)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('sabeta', 6)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('jugorta', 7)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('faas', 8)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('lopiunes', 0)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('grepa', 1)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('lopera', 2)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('sameda', 3)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('ouita56', 4)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('darx666', 5)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('firehead', 6)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('sugoisugoi', 7)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('momo', 8)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('sabeta', 0)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('jugorta', 1)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('faas', 2)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('lopiunes', 3)
into PERSONA_DISPONIBLEXCOLOR_PELO
(USERNAME, COLOR_PELO_ID)
values
('grepa', 4)
SELECT 1 from DUAL;
