INSERT ALL
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('koki', 12)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('gago', 11)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('jua345', 10)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('kkkus', 9)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('rameno', 8)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('tadeo', 7)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('semejis', 6)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('cataclism0', 5)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('lopera', 4)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('sameda', 3)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('ouita56', 2)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('darx666', 1)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('firehead', 0)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('sugoisugoi', 1)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('momo', 2)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('sabeta', 3)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('jugorta', 4)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('faas', 5)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('lopiunes', 6)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('grepa', 7)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('lopera', 8)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('sameda', 9)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('ouita56', 10)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('darx666', 11)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('firehead', 12)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('sugoisugoi', 12)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('momo', 11)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('sabeta', 10)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('jugorta', 9)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('faas', 8)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('lopiunes', 7)
into PERSONA_DISPONIBLEXIDIOMA
(USERNAME, IDIOMA_ID)
values
('grepa', 6)
SELECT 1 from DUAL;
