create or replace procedure INSERT_BEBEDOR(pBEBEDOR_ID IN NUMBER, pTIPO IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO BEBEDOR
  VALUES (pBEBEDOR_ID,pTIPO,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_BEBEDOR;

