create or replace procedure INSERT_EJERCICIO(pEJERCICIO_ID IN NUMBER, NOMBRE IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO EJERCICIO
  VALUES (pEJERCICIO_ID,NOMBRE,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_EJERCICIO;
