create or replace procedure UPDATE_EVENTO(pNOMBRE IN VARCHAR, pFECHA IN DATE, pLUGAR IN VARCHAR, pDESCRIPCION IN VARCHAR, pEVENTO_ID IN NUMBER) is
begin
  update EVENTO
    set NOMBRE = pNOMBRE, FECHA = pFECHA, DESCRIPCION = pDESCRIPCION, LUGAR = pLUGAR
      where EVENTO_id = pEVENTO_ID;
        end UPDATE_EVENTO;
