create or replace procedure UPDATE_PARAMETRO(pPARAMETROS_ID IN VARCHAR, pPARAMETRO_ID IN NUMBER) is
begin
  update PARAMETRO
    set PARAMETROS_ID = pPARAMETROS_ID
      where PARAMETRO_id = pPARAMETRO_ID;
        end UPDATE_PARAMETRO;
