tablas="PAIS CIUDAD GENERO PERSONA FOTO EMAIL COLOR_OJOS COLOR_PELO COLOR_PIEL CONTEXTURA NIVEL_EDUCACION IDIOMA RELIGION ESTADO_CIVIL FUMADOR BEBEDOR FRECUENCIA_EJERCICIO CATEGORIA_OCUPACION OCUPACION SALARIO MASCOTA EJERCICIO CATEGORIA_INTERES INTERES WINK VISITA OCUPACIONXCATEGORIA_OCUPACION INTERESXCATEGORIA_INTERES PERSONA_DISPONIBLE PERSONA_DISPONIBLEXOCUPACION PERSONA_DISPONIBLEXIDIOMA PERSONA_DISPONIBLEXRELIGION PERSONA_DISPONIBLEXMASCOTA PERSONA_DISPONIBLEXEJERCICIO PERSONA_DISPONIBLEXINTERES PERSONA_DISPONIBLEXCOLOR_PELO EVENTO "

i=0
for tabla in $tablas
do
	cat > ${i}_Auditoria_${tabla}.sql <<- END
	alter table $tabla
	add (
	  fec_creacion		DATE,
	  usuario_creacion	VARCHAR2(10),
	  fec_ultima_mod	DATE,
	  usuario_ultima_mod	VARCHAR2(10)
	);
	END
	let i+=1
done
