CREATE OR REPLACE TRIGGER beforeUpdate_per_dispxidioma
       BEFORE UPDATE
       ON GE.PERSONA_DISPONIBLEXIDIOMA FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
