create or replace procedure INSERT_PER_DISPXC_PELO(pUSERNAME IN NUMBER,pES_REAL IN VARCHAR2, pCOLOR_PELO_ID IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO PERSONA_DISPONIBLEXCOLOR_PELO
  VALUES (pUSERNAME,pES_REAL,pCOLOR_PELO_ID,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_PER_DISPXC_PELO;
