create or replace procedure IN_OCUPAXCATEGORIA_OCUPA(pOCUPAXCAT_OCUPA_ID IN NUMBER, CATEGORIA_OCUPACION_ID IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO OCUPACIONXCATEGORIA_OCUPACION
  VALUES (pOCUPAXCAT_OCUPA_ID,CATEGORIA_OCUPACION_ID,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end IN_OCUPAXCATEGORIA_OCUPA;
