create or replace procedure INSERT_PARAMETROS(pPARAMETROS_ID IN NUMBER, pVALOR IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO PARAMETROS
  VALUES (pPARAMETROS_ID,pVALOR,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_PARAMETROS;
