create or replace procedure IN_INTEXCAT_INTE(pINTERES_ID IN NUMBER, CATEGORIA_INTERES_ID IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO INTERESXCATEGORIA_INTERES
  VALUES (pINTERES_ID,CATEGORIA_INTERES_ID,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end IN_INTEXCAT_INTE;
