create or replace procedure INSERT_NIVEL_EDUCACION(pNIVEL_EDUCACION_ID IN NUMBER, GRADO IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO NIVEL_EDUCACION
  VALUES (pNIVEL_EDUCACION_ID,GRADO,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_NIVEL_EDUCACION;
