create or replace procedure INSERT_PERSONA(pUSERNAME IN VARCHAR, pES_ADMIN IN VARCHAR, pNACIMIENTO IN VARCHAR, pPRIMER_APELLIDO IN VARCHAR, pSEGUNDO_APELLIDO IN VARCHAR, pNOMBRE IN VARCHAR, pGENERO_ID IN VARCHAR, pCIUDAD_ID IN VARCHAR,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO PERSONA
  VALUES (pUSERNAME, pES_ADMIN, pNACIMIENTO, pPRIMER_APELLIDO, pSEGUNDO_APELLIDO, pNOMBRE, pGENERO_ID, pCIUDAD_ID,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_PERSONA;
