create or replace procedure INSERT_CONTEXTURA(pCONTEXTURA_ID IN NUMBER, TIPO IN VARCHAR2,FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO CONTEXTURA
  VALUES (pCONTEXTURA_ID,TIPO,FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_CONTEXTURA;
