create or replace procedure INSERT_FOTO(pFOTO_ID IN NUMBER, pNOMBRE IN VARCHAR2,pRUTA IN NUMBER, pUSERNAME IN VARCHAR2, FEC_CREACION IN DATE, USUARIO_CREACION IN VARCHAR, FEC_ULTIMA_MOD IN DATE, USUARIO_ULTIMA_MOD IN VARCHAR2  ) is
begin
  INSERT INTO FOTO
  VALUES (pFOTO_ID,pNOMBRE,pRUTA, pUSERNAME, FEC_CREACION , USUARIO_CREACION , FEC_ULTIMA_MOD, USUARIO_ULTIMA_MOD );
  
end INSERT_FOTO;
