CREATE OR REPLACE PROCEDURE BUSCAR_POR_CIUDAD
(
  pCIUDAD_ID IN PERSONA.CIUDAD_ID%TYPE,
  p_recordset OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_recordset FOR
SELECT *
FROM PERSONA
where ciudad_id = pCIUDAD_ID;
END;
/

