CREATE TYPE string_table AS TABLE OF varchar2(500);
CREATE OR REPLACE PROCEDURE PERSONAS_POR_CIUDADES
(
  pCIUDAD_ID IN PERSONA.CIUDAD_ID%TYPE,
  p_recordset OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_recordset FOR
SELECT COUNT(PERSONA.CIUDAD_ID), get_ciudad(PERSONA.CIUDAD_ID) 
FROM PERSONA
GROUP BY PERSONA.CIUDAD_ID;

END PERSONAS_POR_CIUDAD;
/

