CREATE OR REPLACE PROCEDURE CONSULTA_POR_NOMBRE(pNOMBRE IN PERSONA.NOMBRE, P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
  SELECT *
FROM PERSONA
WHERE PERSONA.NOMBRE = pNOMBRE;
END CONSULTA_POR_NOMBRE;
  
