CREATE OR REPLACE PROCEDURE CONSULTA_POR_NOMBRE(pNOMBRE IN PERSONA.NOMBRE%TYPE, P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
SELECT PERSONA.USERNAME,
  PERSONA.NOMBRE AS NOMBRE,
  PERSONA.PRIMER_APELLIDO AS PRIMER_APELLIDO,
  PERSONA.SEGUNDO_APELLIDO AS SEGUNDO_APELLIDO,
  GENERO.NOMBRE              AS GENERO,
  RELIGION.NOMBRE AS RELIGION,
  SALARIO.RANGO AS SALARIO,
  OCUPACION.NOMBRE AS OCUPACIÓN,
  ESTADO_CIVIL.NOMBRE      AS ESTADO_CIVIL,
  INTERES.NOMBRE AS INTERES,
  MASCOTA.TIPO             AS MASCOTA,
  CONTEXTURA.TIPO          AS CONTEXTURA,
  BEBEDOR.TIPO AS BEBEDOR,
  IDIOMA.NOMBRE            AS IDIOMA,
  COLOR_PIEL.NOMBRE        AS COLOR_DE_PIEL,
  COLOR_PELO.NOMBRE       AS COLOR_DE_PELO,
  COLOR_OJOS.NOMBRE        AS COLOR_DE_OJOS,
  PERSONA_DISPONIBLE.ALTURA AS ALTURA,
  PERSONA_DISPONIBLE.PESO AS PESO,
  PERSONA_DISPONIBLE.NUM_HIJOS AS NUM_HIJOS,
  PERSONA_DISPONIBLE.QUIERE_HIJOS AS QUIERE_HIJOS,
  EJERCICIO.NOMBRE AS EJERCICIO,
  NIVEL_EDUCACION.GRADO AS GRADO,
  FUMADOR.TIPO               AS FUMADOR,
  CATEGORIA_OCUPACION.NOMBRE AS CAT_OCUPACION,
  CIUDAD.NOMBRE  AS CIUDAD,
  PAIS.NOMBRE      AS PAÍS,
  PERSONA.SLOGAN AS SLOGAN,
  FOTO.NOMBRE              AS FOTO

FROM PERSONA                   

WHERE PERSONA.NOMBRE = pNOMBRE;
END CONSULTA_POR_NOMBRE;
