CREATE OR REPLACE PROCEDURE PERSONAS_POR_PAIS(pPais_ID IN CIUDAD.PAIS_ID%TYPE, P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
SELECT COUNT(PAIS.pais_id) AS "Personas por país",
  PAIS.nombre
FROM PERSONA

INNER JOIN CIUDAD
ON PERSONA.CIUDAD_ID = CIUDAD.CIUDAD_ID

INNER JOIN PAIS
ON CIUDAD.PAIS_ID = PAIS.PAIS_ID

WHERE PAIS.PAIS_ID = pPais_ID
GROUP BY PAIS.nombre;
END PERSONAS_POR_PAIS;
