CREATE OR REPLACE PROCEDURE PERSONAS_POR_PAIS(pPais_ID IN PERSONA.PAIS_ID%TYPE, P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
  SELECT COUNT (NOMBRE) AS "Personas por Pais"
FROM PERSONA
WHERE PAIS_ID = pPais_ID;
END PERSONAS_POR_PAIS;
