CREATE OR REPLACE PROCEDURE PERSONAS_XPAIS(pPAIS_ID IN CIUDAD.PAIS_ID%TYPE, P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
  SELECT COUNT (NOMBRE) AS "Personas por Pais"
FROM CIUDAD INNER JOIN PAIS pPais
WHERE CIUDAD.PAIS_ID = PAIS.PAIS_ID;
END PERSONAS_POR_PAIS;
