CREATE OR REPLACE PROCEDURE PERSONAS_POR_CIUDAD
(
  pCIUDAD_ID IN PERSONA.CIUDAD_ID%TYPE,
  p_recordset OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_recordset FOR
  SELECT COUNT (NOMBRE) AS "Personas por Ciudad"
FROM PERSONA
WHERE CIUDAD_ID = pCIUDAD_ID;
END PERSONAS_POR_CIUDAD;
