CREATE OR REPLACE PROCEDURE personas_por_genero (pGENERO IN persona.genero_id%TYPE,
p_recordset OUT SYS_REFCURSOR) AS
BEGIN
    OPEN p_recordset FOR
SELECT GENERO.NOMBRE AS GÉNERO,
  COUNT(PERSONA.USERNAME) AS "Total personas por género"
FROM GENERO 
INNER JOIN PERSONA
ON PERSONA.GENERO_ID = GENERO.GENERO_ID
WHERE PERSONA.GENERO_ID = pGENERO
GROUP BY GENERO.NOMBRE,
  PERSONA.GENERO_ID;

END personas_por_genero;
