CREATE OR REPLACE PROCEDURE PERSONAS_POR_ESTADO
(
  pESTADO_CIVIL_ID IN PERSONA_DISPONIBLE.ESTADO_CIVIL_ID%TYPE,
  p_recordset OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_recordset FOR
SELECT COUNT(PERSONA_DISPONIBLE.ESTADO_CIVIL_ID) AS "Personas por ESTADO_CIVIL",
       ESTADO_CIVIL.nombre

FROM PERSONA_DISPONIBLE
INNER JOIN ESTADO_CIVIL
ON PERSONA_DISPONIBLE.ESTADO_CIVIL_ID = ESTADO_CIVIL.ESTADO_CIVIL_ID

WHERE ESTADO_CIVIL.ESTADO_CIVIL_ID = pESTADO_CIVIL_ID
GROUP BY ESTADO_CIVIL.NOMBRE;

END PERSONAS_POR_ESTADO;
