CREATE OR REPLACE PROCEDURE TOTAL_PERSONAS_REGISTRADAS(P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
  SELECT COUNT(*) AS "Personas Registradas"*
FROM PERSONAS
END TOTAL_PERSONAS_REGISTRADAS;
