CREATE OR REPLACE PROCEDURE TOTAL_PERSONAS_REGISTRADAS(P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
SELECT COUNT(PERSONA.USERNAME) AS "Total de personas registradas" 
FROM PERSONA;
END TOTAL_PERSONAS_REGISTRADAS;
