

CREATE OR REPLACE PROCEDURE TOTAL_MATCH(P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
  SELECT COUNT(PERSONA_DISPONIBLE.MATCH) AS "Total de Parejas"
FROM PERSONA_DISPONIBLE
WHERE PERSONA_DISPONIBLE.MATCH = 'Si';
END TOTAL_MATCH;
