

CREATE OR REPLACE PROCEDURE TOTAL_MATRIMONIOS(P_RECORDSET OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN P_RECORDSET FOR
  SELECT COUNT(PERSONA_DISPONIBLE.MATRIMONIO) AS "Total de Matrimonios"
FROM PERSONA_DISPONIBLE
WHERE PERSONA_DISPONIBLE.MATRIMONIO = 'Si';
END TOTAL_MATRIMONIOS;
