<?php
$dalTableINTERESXCATEGORIA_INTERES = array();
$dalTableINTERESXCATEGORIA_INTERES["INTERES_ID"] = array("type"=>14,"varname"=>"INTERES_ID");
$dalTableINTERESXCATEGORIA_INTERES["CATEGORIA_INTERES_ID"] = array("type"=>14,"varname"=>"CATEGORIA_INTERES_ID");
$dalTableINTERESXCATEGORIA_INTERES["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTableINTERESXCATEGORIA_INTERES["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTableINTERESXCATEGORIA_INTERES["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTableINTERESXCATEGORIA_INTERES["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
	$dalTableINTERESXCATEGORIA_INTERES["INTERES_ID"]["key"]=true;
	$dalTableINTERESXCATEGORIA_INTERES["CATEGORIA_INTERES_ID"]["key"]=true;
$dal_info["INTERESXCATEGORIA_INTERES"]=&$dalTableINTERESXCATEGORIA_INTERES;

?>