<?php
$dalTableOCUPACIONXCATEGORIA_OCUPACION = array();
$dalTableOCUPACIONXCATEGORIA_OCUPACION["OCUPACION_ID"] = array("type"=>14,"varname"=>"OCUPACION_ID");
$dalTableOCUPACIONXCATEGORIA_OCUPACION["CATEGORIA_OCUPACION_ID"] = array("type"=>14,"varname"=>"CATEGORIA_OCUPACION_ID");
$dalTableOCUPACIONXCATEGORIA_OCUPACION["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTableOCUPACIONXCATEGORIA_OCUPACION["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTableOCUPACIONXCATEGORIA_OCUPACION["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTableOCUPACIONXCATEGORIA_OCUPACION["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
	$dalTableOCUPACIONXCATEGORIA_OCUPACION["OCUPACION_ID"]["key"]=true;
	$dalTableOCUPACIONXCATEGORIA_OCUPACION["CATEGORIA_OCUPACION_ID"]["key"]=true;
$dal_info["OCUPACIONXCATEGORIA_OCUPACION"]=&$dalTableOCUPACIONXCATEGORIA_OCUPACION;

?>