<?php
$dalTablePERSONA_DISPONIBLEXIDIOMA = array();
$dalTablePERSONA_DISPONIBLEXIDIOMA["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXIDIOMA["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXIDIOMA["IDIOMA_ID"] = array("type"=>14,"varname"=>"IDIOMA_ID");
$dalTablePERSONA_DISPONIBLEXIDIOMA["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXIDIOMA["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXIDIOMA["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXIDIOMA["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXIDIOMA"]=&$dalTablePERSONA_DISPONIBLEXIDIOMA;

?>