<?php
$dalTablePERSONA_DISPONIBLEXOCUPACION = array();
$dalTablePERSONA_DISPONIBLEXOCUPACION["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXOCUPACION["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXOCUPACION["OCUPACION_ID"] = array("type"=>14,"varname"=>"OCUPACION_ID");
$dalTablePERSONA_DISPONIBLEXOCUPACION["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXOCUPACION["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXOCUPACION["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXOCUPACION["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXOCUPACION"]=&$dalTablePERSONA_DISPONIBLEXOCUPACION;

?>