<?php
$dalTablePERSONA_DISPONIBLEXEJERCICIO = array();
$dalTablePERSONA_DISPONIBLEXEJERCICIO["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXEJERCICIO["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXEJERCICIO["EJERCICIO_ID"] = array("type"=>14,"varname"=>"EJERCICIO_ID");
$dalTablePERSONA_DISPONIBLEXEJERCICIO["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXEJERCICIO["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXEJERCICIO["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXEJERCICIO["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXEJERCICIO"]=&$dalTablePERSONA_DISPONIBLEXEJERCICIO;

?>