<?php
$dalTablePERSONA_DISPONIBLEXMASCOTA = array();
$dalTablePERSONA_DISPONIBLEXMASCOTA["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXMASCOTA["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXMASCOTA["MASCOTA_ID"] = array("type"=>14,"varname"=>"MASCOTA_ID");
$dalTablePERSONA_DISPONIBLEXMASCOTA["CANTIDAD"] = array("type"=>14,"varname"=>"CANTIDAD");
$dalTablePERSONA_DISPONIBLEXMASCOTA["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXMASCOTA["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXMASCOTA["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXMASCOTA["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXMASCOTA"]=&$dalTablePERSONA_DISPONIBLEXMASCOTA;

?>