<?php
$dalTablePERSONA_DISPONIBLEXRELIGION = array();
$dalTablePERSONA_DISPONIBLEXRELIGION["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXRELIGION["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXRELIGION["RELIGION_ID"] = array("type"=>14,"varname"=>"RELIGION_ID");
$dalTablePERSONA_DISPONIBLEXRELIGION["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXRELIGION["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXRELIGION["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXRELIGION["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXRELIGION"]=&$dalTablePERSONA_DISPONIBLEXRELIGION;

?>