<?php
$dalTablePERSONA_DISPONIBLEXINTERES = array();
$dalTablePERSONA_DISPONIBLEXINTERES["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXINTERES["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXINTERES["INTERES_ID"] = array("type"=>14,"varname"=>"INTERES_ID");
$dalTablePERSONA_DISPONIBLEXINTERES["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXINTERES["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXINTERES["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXINTERES["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXINTERES"]=&$dalTablePERSONA_DISPONIBLEXINTERES;

?>