<?php
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO = array();
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["USERNAME"] = array("type"=>200,"varname"=>"USERNAME");
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["ES_REAL"] = array("type"=>200,"varname"=>"ES_REAL");
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["COLOR_PELO_ID"] = array("type"=>14,"varname"=>"COLOR_PELO_ID");
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["FEC_CREACION"] = array("type"=>135,"varname"=>"FEC_CREACION");
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["USUARIO_CREACION"] = array("type"=>200,"varname"=>"USUARIO_CREACION");
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["FEC_ULTIMA_MOD"] = array("type"=>135,"varname"=>"FEC_ULTIMA_MOD");
$dalTablePERSONA_DISPONIBLEXCOLOR_PELO["USUARIO_ULTIMA_MOD"] = array("type"=>200,"varname"=>"USUARIO_ULTIMA_MOD");
$dal_info["PERSONA_DISPONIBLEXCOLOR_PELO"]=&$dalTablePERSONA_DISPONIBLEXCOLOR_PELO;

?>