CREATE OR REPLACE TRIGGER beforeInsert_per_dispxreligion
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXRELIGION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
