CREATE OR REPLACE TRIGGER beforeInsert_per_dispxejerc
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXEJERCICIO FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
