CREATE OR REPLACE TRIGGER beforeUpdate_per_dispxc_pelo
       BEFORE UPDATE
       ON GE.PERSONA_DISPONIBLEXCOLOR_PELO FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
