-- GE: DATA
CREATE TABLESPACE GE_Data
DATAFILE 'C:\BDMatchMe\gedata01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;
--
-- GE: INDEX
CREATE TABLESPACE GE_Ind
DATAFILE 'C:\BDMatchMe\geind01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;
