CREATE OR REPLACE TRIGGER beforeUpdate_ocuxcat_ocupacion
       BEFORE UPDATE
       ON GE.OCUPACIONXCATEGORIA_OCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
