CREATE OR REPLACE TRIGGER beforeInsert_pais
       BEFORE INSERT
       ON GE.PAIS FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_pais
       BEFORE UPDATE
       ON GE.PAIS FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
