CREATE OR REPLACE TRIGGER beforeInsert_nivel_educacion
       BEFORE INSERT
       ON GE.NIVEL_EDUCACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_nivel_educacion
       BEFORE UPDATE
       ON GE.NIVEL_EDUCACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
