CREATE OR REPLACE TRIGGER beforeInsert_idioma
       BEFORE INSERT
       ON GE.IDIOMA FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_idioma
       BEFORE UPDATE
       ON GE.IDIOMA FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
