CREATE OR REPLACE TRIGGER beforeInsert_estado_civil
       BEFORE INSERT
       ON GE.ESTADO_CIVIL FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_estado_civil
       BEFORE UPDATE
       ON GE.ESTADO_CIVIL FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
