CREATE OR REPLACE TRIGGER beforeInsert_fumador
       BEFORE INSERT
       ON GE.FUMADOR FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_fumador
       BEFORE UPDATE
       ON GE.FUMADOR FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
