CREATE OR REPLACE TRIGGER beforeInsert_frecuencia_ejercicio
       BEFORE INSERT
       ON GE.FRECUENCIA_EJERCICIO FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
