CREATE OR REPLACE TRIGGER beforeInsert_categoria_ocupacion
       BEFORE INSERT
       ON GE.CATEGORIA_OCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
