CREATE OR REPLACE TRIGGER beforeInsert_ciudad
       BEFORE INSERT
       ON GE.CIUDAD FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_ciudad
       BEFORE UPDATE
       ON GE.CIUDAD FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
