CREATE OR REPLACE TRIGGER beforeInsert_mascota
       BEFORE INSERT
       ON GE.MASCOTA FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_mascota
       BEFORE UPDATE
       ON GE.MASCOTA FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
