CREATE OR REPLACE TRIGGER beforeInsert_ejercicio
       BEFORE INSERT
       ON GE.EJERCICIO FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_ejercicio
       BEFORE UPDATE
       ON GE.EJERCICIO FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
