CREATE OR REPLACE TRIGGER beforeInsert_categoria_interes
       BEFORE INSERT
       ON GE.CATEGORIA_INTERES FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_categoria_interes
       BEFORE UPDATE
       ON GE.CATEGORIA_INTERES FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
