CREATE OR REPLACE TRIGGER beforeInsert_wink
       BEFORE INSERT
       ON GE.WINK FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_wink
       BEFORE UPDATE
       ON GE.WINK FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
