CREATE OR REPLACE TRIGGER beforeInsert_ocupacionxcategoria_ocupacion
       BEFORE INSERT
       ON GE.OCUPACIONXCATEGORIA_OCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
