CREATE OR REPLACE TRIGGER beforeInsert_ocupacionxcategoria_ocupacion
       BEFORE INSERT
       ON GE.OCUPACIONXCATEGORIA_OCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_ocupacionxcategoria_ocupacion
       BEFORE UPDATE
       ON GE.OCUPACIONXCATEGORIA_OCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
