CREATE OR REPLACE TRIGGER beforeInsert_interesxcat_int
       BEFORE INSERT
       ON GE.INTERESXCATEGORIA_INTERES FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
