CREATE OR REPLACE TRIGGER beforeInsert_interesxcategoria_interes
       BEFORE INSERT
       ON GE.INTERESXCATEGORIA_INTERES FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
