CREATE OR REPLACE TRIGGER beforeUpdate_interesxcategoria_interes
       BEFORE UPDATE
       ON GE.INTERESXCATEGORIA_INTERES FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
