CREATE OR REPLACE TRIGGER beforeUpdate_persona_disponible
       BEFORE UPDATE
       ON GE.PERSONA_DISPONIBLE FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
