CREATE OR REPLACE TRIGGER beforeInsert_persona_disponiblexocupacion
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXOCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_persona_disponiblexocupacion
       BEFORE UPDATE
       ON GE.PERSONA_DISPONIBLEXOCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
