CREATE OR REPLACE TRIGGER beforeInsert_persona_disponiblexocupacion
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXOCUPACION FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
