CREATE OR REPLACE TRIGGER beforeInsert_persona_disponiblexidioma
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXIDIOMA FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
