CREATE OR REPLACE TRIGGER beforeUpdate_per_dispxreligion
       BEFORE UPDATE
       ON GE.PERSONA_DISPONIBLEXRELIGION FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
