CREATE OR REPLACE TRIGGER beforeInsert_per_dispxmascota
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXMASCOTA FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
