CREATE OR REPLACE TRIGGER beforeInsert_persona_disponiblexejercicio
       BEFORE INSERT
       ON GE.PERSONA_DISPONIBLEXEJERCICIO FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
