CREATE OR REPLACE TRIGGER beforeInsert_evento
       BEFORE INSERT
       ON GE.EVENTO FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_evento
       BEFORE UPDATE
       ON GE.EVENTO FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
