CREATE OR REPLACE TRIGGER beforeInsert_persona
       BEFORE INSERT
       ON GE.PERSONA FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_persona
       BEFORE UPDATE
       ON GE.PERSONA FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
