CREATE OR REPLACE TRIGGER beforeInsert_email
       BEFORE INSERT
       ON GE.EMAIL FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_email
       BEFORE UPDATE
       ON GE.EMAIL FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
