CREATE OR REPLACE TRIGGER beforeInsert_color_piel
       BEFORE INSERT
       ON GE.COLOR_PIEL FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_color_piel
       BEFORE UPDATE
       ON GE.COLOR_PIEL FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
