CREATE OR REPLACE TRIGGER beforeInsert_contextura
       BEFORE INSERT
       ON GE.CONTEXTURA FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;
CREATE OR REPLACE TRIGGER beforeUpdate_contextura
       BEFORE UPDATE
       ON GE.CONTEXTURA FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MOD:= USER;
  :NEW.FEC_ULTIMA_MOD:= SYSDATE;
END;
